#!/usr/bin/python
'''
Property default values and writablity flagging
'''

from bacpypes.primitivedata import *
from bacpypes.constructeddata import *
from bacpypes.basetypes import *

defaultObjectReference = ObjectPropertyReference(
    objectIdentifier=('analogInput', 4194303),
    propertyIdentifier='presentValue',
)
defaultDeviceObjectReference = DeviceObjectPropertyReference(
    objectIdentifier=('analogInput', 4194303),
    propertyIdentifier='presentValue',
)
defaultEventParameter = EventParameter(
    outOfRange=EventParameterOutOfRange(
        timeDelay=0,
        lowLimit=0,
        highLimit=0,
        deadband=0,
    )
)
defaultAccumulatorRecord = AccumulatorRecord(
    timestamp = DateTime(date=Date(), time=Time()),
    presentValue = 0,
    accumulatedValue = 0,
    accumulatorStatus = 'normal',
)
defaultEventTimestamps = ArrayOf(TimeStamp)([TimeStamp(dateTime=DateTime(date=Date(), time=Time())) for i in range(3)])
defaultEventMessageTexts = ArrayOf(CharacterString)(['','',''])
defaultDateTime = DateTime(date=Date(), time=Time())

present_value_defaults = {
    'default':              0,
    'bitstringValue':       [0],
    'calendar':             False,
    'characterstringValue': '',
    'datePatternValue':     Date(),
    'dateValue':            Date((0,0,0,0)),
    'datetimePatternValue': DateTime(date=Date(), time=Time()),
    'datetimeValue':        DateTime(date=Date((0,0,0,0)), time=Time((0,0,0,0))),
    'globalGroup':          [],
    'group':                [],
    'multiStateInput':      1,
    'multiStateOutput':     1,
    'multiStateValue':      1,
    'octetstringValue':     '',
    'schedule':             Null(),
    'timePatternValue':     Time(),
    'timeValue':            Time((0,0,0,0)),
}

relinquish_defaults = {
    'default':              0,
    'bitstringValue':       [0],
    'characterstringValue': '',
    'datePatternValue':     Date(),
    'dateValue':            Date((0,0,0,0)),
    'datetimePatternValue': DateTime(date=Date(), time=Time()),
    'datetimeValue':        DateTime(date=Date((0,0,0,0)), time=Time((0,0,0,0))),
    'multiStateOutput':     1,
    'multiStateValue':      1,
    'octetstringValue':     b'0',
    'timePatternValue':     Time(),
    'timeValue':            Time((0,0,0,0)),
}

profile_defaults = {
    'accumulator':          '15-ACCUMULATOR',
    'analogInput':          '15-ANALOGINPUT',
    'analogOutput':         '15-ANALOGOUTPUT',
    'analogValue':          '15-ANALOGVALUE',
    'averaging':            '15-AVERAGING',
    'binaryInput':          '15-BINARYINPUT',
    'binaryOutput':         '15-BINARYOUTPUT',
    'binaryLightingOutput': '15-BINARYLIGHTINGOUTPUT',
    'binaryValue':          '15-BINARYVALUE',
    'bitstringValue':       '15-BITSTRINGVALUE',
    'calendar':             '15-CALENDAR',
    'characterstringValue': '15-CHARACTERSTRINGVALUE',
    'command':              '15-COMMAND',
    'datePatternValue':     '15-DATEPATTERNVALUE',
    'dateValue':            '15-DATEVALUE',
    'datetimePatternValue': '15-DATETIMEPATTERNVALUE',
    'datetimeValue':        '15-DATETIMEVALUE',
    'device':               '15-DEVICE',
    'eventEnrollment':      '15-EVENTENROLLMENT',
    'eventLog':             '15-EVENTLOG',
    'file':                 '15-FILE',
    'globalGroup':          '15-GLOBALGROUP',
    'group':                '15-GROUP',
    'integerValue':         '15-INTEGERVALUE',
    'largeAnalogValue':     '15-LARGEANALOGVALUE',
    'lightingOutput':       '15-LIGHTINGOUTPUT',
    'loadControl':          '15-LOADCONTROL',
    'loop':                 '15-LOOP',
    'multiStateInput':      '15-MULTISTATEINPUT',
    'multiStateOutput':     '15-MULTISTATEOUTPUT',
    'multiStateValue':      '15-MULTISTATEVALUE',
    'notificationClass':    '15-NOTIFICATIONCLASS',
    'octetstringValue':     '15-OCTETSTRINGVALUE',
    'positiveIntegerValue': '15-POSITIVEINTEGERVALUE',
    'program':              '15-PROGRAM',
    'pulseConverter':       '15-PULSECONVERTER',
    'schedule':             '15-SCHEDULE',
    'structuredView':       '15-STRUCTUREDVIEW',
    'timePatternValue':     '15-TIMEPATTERNVALUE',
    'timeValue':            '15-TIMEVALUE',
    'trendLog':             '15-TRENDLOG',
    'trendLogMultiple':     '15-TRENDLOGMULTIPLE',
}

default_property_values = {
  'ackRequired':                      { 'default': [1,1,1] },
  'ackedTransitions':                 { 'default': [1,1,1] },
  'action':                           { 'default': 'direct', 'command': [] },
  'actionText':                       { 'default': [] },
  'activeCovSubscriptions':           { 'default': [] },
  'activeText':                       { 'default': '' },
  'actualShedLevel':                  { 'default': ShedLevel(percent=0) },
  'adjustValue':                      { 'default': 0 },
  'alarmValue':                       { 'default': 'active' },
  'alarmValues':                      { 'default': [] },
  'alignIntervals':                   { 'default': False  },
  'allWritesSuccessful':              { 'default': True  },
  'archive':                          { 'default': False },
  'attemptedSamples':                 { 'default': 0 },
  'averageValue':                     { 'default': -float('nan') },
  'bias':                             { 'default': 0 },
  'bitMask':                          { 'default': [0] },
  'bitText':                          { 'default': ['Bit 1'] },
  'blinkWarnEnable':                  { 'default': False },
  'bufferSize':                       { 'default': 100 },
  'changeOfStateCount':               { 'default': 0 },
  'changeOfStateTime':                { 'default': defaultDateTime },
  'clientCovIncrement':               { 'default': ClientCOV(defaultIncrement=Null()) },
  'commandTimeArray':                 { 'default': ArrayOf(TimeStamp)([TimeStamp(dateTime=DateTime(date=Date(), time=Time())) for i in range(16)]) },
  'controlledVariableReference':      { 'default': defaultObjectReference },
  'controlledVariableUnits':          { 'default': 'noUnits' },
  'controlledVariableValue':          { 'default': 0 },
  'count':                            { 'default': 0 },
  'countBeforeChange':                { 'default': 0 },
  'countChangeTime':                  { 'default': defaultDateTime },
  'covIncrement':                     { 'default': 1 },
  'covPeriod':                        { 'default': 100 },
  'covResubscriptionInterval':        { 'default': 600 },
  'covuPeriod':                       { 'default': 100 },
  'covuRecipients':                   { 'default': [] },
  'dateList':                         { 'default': [] },
  'daylightSavingsStatus':            { 'default': False },
  'deadband':                         { 'default': 0 },
  'defaultFadeTime':                  { 'default': 5000},
  'defaultRampRate':                  { 'default': 10},
  'defaultStepIncrement':             { 'default': 1.0},
  'defaultTimeout':                   { 'default': 0},
  'derivativeConstant':               { 'default': 0 },
  'derivativeConstantUnits':          { 'default': 'noUnits' },
  'description':                      { 'default': '' },
  'descriptionOfHalt':                { 'default': '' },
  'deviceAddressBinding':             { 'default': [] },
  'deviceType':                       { 'default': '' },
  'dutyWindow':                       { 'default': 10 },
  'effectivePeriod':                  { 'default': DateRange(startDate=Date(), endDate=Date()) },
  'egressActive':                     { 'default': False },
  'egressTime':                       { 'default': 1 },
  'elapsedActiveTime':                { 'default': 0 },
  'enable':                           { 'default': False },
  'errorLimit':                       { 'default': 0 },
  'eventAlgorithmInhibit':            { 'default': False },
  'eventAlgorithmInhibitRef':         { 'default': ObjectPropertyReference(
                                                    objectIdentifier = ("analogInput", 0),
                                                    propertyIdentifier = PropertyIdentifier('presentValue'),
                                                    propertyArrayIndex = 0
                                                   ), },
  'eventDetectionEnable':             { 'default': False },
  'eventEnable':                      { 'default': [0,0,0] },
  'eventMessageTexts':                { 'default': defaultEventMessageTexts },
  'eventMessageTextsConfig':          { 'default': defaultEventMessageTexts },
  'eventState':                       { 'default': 'normal' },
  'eventTimeStamps':                  { 'default': defaultEventTimestamps },
  'eventType':                        { 'default': 'outOfRange' },
  'eventParameters':                  { 'default': defaultEventParameter },
  'exceptionSchedule':                { 'default': ArrayOf(SpecialEvent)([])},
  'expectedShedLevel':                { 'default': ShedLevel(percent=0) },
  'expirationTime':                   { 'default': defaultDateTime },
  'faultHighLimit':                   { 'default': 0 },
  'faultLowLimit':                    { 'default': 0 },
  'faultValues':                      { 'default': [] },
  'feedbackValue':                    { 'default': 0 },
  'fileAccessMethod':                 { 'default': 'recordAccess' },
  'fileSize':                         { 'default': 0 },
  'fileType':                         { 'default': '' },
  'fullDutyBaseline':                 { 'default': 0 },
  'groupMembers':                     { 'default': [] },
  'groupMemberNames':                 { 'default': [] },  
  'highLimit':                        { 'default': 0 },
  'inactiveText':                     { 'default': '' },
  'initialTimeout':                   { 'default': 0},
  'inProcess':                        { 'default': False },
  'inProgress':                       { 'default': 'idle' },
  'inputReference':                   { 'default': defaultObjectReference },
  'instanceOf':                       { 'default': '' },
  'instantaneousPower':               { 'default': 1.0 },
  'integralConstant':                 { 'default': 0 },
  'integralConstantUnits':            { 'default': 'noUnits' },
  'intervalOffset':                   { 'default': 0 },
  'isUTC':                            { 'default': False },
  'lastNotifyRecord':                 { 'default': 0 },  
  'lastCommandTime':                  { 'default': TimeStamp(dateTime=DateTime(date=Date(), time=Time())) },
  'lastStateChange':                  { 'default': 'none'},
  'lightingCommand':                  { 'default': LightingCommand(operation = 'none', targetLevel = 50.0, rampRate = 10.0, stepIncrement = 10.0, fadeTime = 5000, priority = 16),},
  'lightingCommandDefaultPriority':   { 'default': 15 }, 
  'limitEnable':                      { 'default': [0,0] },  
  'limitMonitoringInterval':          { 'default': 0 },
  'listOfGroupMembers':               { 'default': [] },
  'listOfObjectPropertyReferences':   { 'default': [] },
  'location':                         { 'default': '' },
  'logBuffer':                        { 'default': 0 },
  'logDeviceObjectProperty':          { 'default': defaultDeviceObjectReference },
  'logInterval':                      { 'default': 0 },
  'loggingObject':                    { 'default': ('analogInput', 4194303) },
  'loggingRecord':                    { 'default': defaultAccumulatorRecord },
  'loggingType':                      { 'default': 'cov' },
  'lowLimit':                         { 'default': 0 },
  'manipulatedVariableReference':     { 'default': defaultObjectReference },
  'maxActualValue':                   { 'default': 100 },
  'maximumOutput':                    { 'default': 0 },
  'maximumValue':                     { 'default': float('-inf')  },
  'maximumValueTimestamp':            { 'default': defaultDateTime },
  'maxPresValue':                     { 'default': 0 },
  'memberStatusFlags':                { 'default': [0,0,0,0] },
  'minActualValue':                   { 'default': 1 },
  'minimumOffTime':                   { 'default': 0 },
  'minimumOnTime':                    { 'default': 0 },
  'minimumOutput':                    { 'default': 0 },
  'minimumValue':                     { 'default': float('inf') },
  'minimumValueTimestamp':            { 'default': defaultDateTime },
  'minPresValue':                     { 'default': 0 },
  'modificationDate':                 { 'default': defaultDateTime },
  'nodeSubtype':                      { 'default': '' },
  'nodeType':                         { 'default': 'unknown' },  
  'notificationClass':                { 'default': 4194303, 'notificationClass': 0 },
  'notificationThreshold':            { 'default': 1 },   
  'notifyType':                       { 'default': 'alarm' },
  'numberOfStates':                   { 'default': 1 },
  'objectPropertyReference':          { 'default': defaultDeviceObjectReference },
  'outOfService':                     { 'default': False },
  'outputUnits':                      { 'default': 'noUnits' },
  'polarity':                         { 'default': 'normal' },
  'power':                            { 'default': 1.0 },
  'prescale':                         { 'default': Prescale(multiplier=1, moduloDivide=1) },
  'presentValue':                     present_value_defaults,
  'priority':                         { 'default': ArrayOf(Unsigned)([255,255,255])},
  'priorityArray':                    { 'default': PriorityArray() },
  'priorityForWriting':               { 'default': 16 },
  'profileLocation':                  { 'default': '' },  
  'profileName':                      profile_defaults,
  'programChange':                    { 'default': 'ready' },
  'programLocation':                  { 'default': '' },
  'programState':                     { 'default': 'idle' },
  'proportionalConstant':             { 'default': 0 },
  'proportionalConstantUnits':        { 'default': 'noUnits' },
  'protocolObjectTypesSupported':     { 'default': [1 for i in range(55)] },
  'pulseRate':                        { 'default': 0 },
  'readOnly':                         { 'default': False },
  'reasonForHalt':                    { 'default': 'normal' },
  'recipientList':                    { 'default': [] },
  'recordCount':                      { 'default': 0 },
  'recordsSinceNotification':         { 'default': 0 },
  'reliability':                      { 'default': 'noFaultDetected' },
  'reliabilityEvaluationInhibit':     { 'default': False },
  'relinquishDefault':                relinquish_defaults,
  'requestedShedLevel':               { 'default': ShedLevel(percent=0) },
  'requestedUpdateInterval':          { 'default': 0 },
  'resolution':                       { 'default': 0 },
  'restartNotificationRecipients':    { 'default': [] },
  'serialNumber':                     { 'default': '' },
  'scale':                            { 'default': Scale(floatScale=1.0) },
  'scaleFactor':                      { 'default': 1 },
  'scheduleDefault':                  { 'default': Null() },
  'setpoint':                         { 'default': 0 },
  'setpointReference':                { 'default': SetpointReference() },
  'shedDuration':                     { 'default': 0 },
  'shedLevelDescriptions':            { 'default': ArrayOf(CharacterString) },
  'shedLevels':                       { 'default': [] },
  'startTime':                        { 'default': defaultDateTime },
  'stateDescription':                 { 'default': '' },
  'stateText':                        { 'default': ['State 1'] },
  'statusFlags':                      { 'default': [0,0,0,0] },
  'stopTime':                         { 'default': defaultDateTime },
  'stopWhenFull':                     { 'default': False },
  'strikeCount':                      { 'default': 0 },
  'structuredObjectList':             { 'default': [] },
  'subordinateAnnotations':           { 'default': [] },
  'subordinateList':                  { 'default': [] },
  'systemStatus':                     { 'default': 'operational' },
  'tags':                             { 'default': ArrayOf(NameValue)() },
  'timeOfActiveTimeReset':            { 'default': defaultDateTime },
  'timeDelay':                        { 'default': 0 },
  'timeDelayNormal':                  { 'default': 0 },
  'timeOfDeviceRestart':              { 'default': TimeStamp(dateTime=DateTime(date=Date(), time=Time())) },
  'timeOfStateCountReset':            { 'default': defaultDateTime },
  'timeOfStrikeCountReset':           { 'default': DateTime(date=Date(), time=Time()) },
  'timerState':                       { 'default': 'idle' },
  'timerRunning':                     { 'default': False },
  'timeSynchronizationInterval':      { 'default': 3600 },
  'timeSynchronizationRecipients':    { 'default': [] },
  'totalRecordCount':                 { 'default': 0 },
  'trackingValue':                    { 'default': 1.0 },
  'trigger':                          { 'default': False },
  'units':                            { 'default': 'noUnits' },
  'updateInterval':                   { 'default': 0 },
  'updateTime':                       { 'default': defaultDateTime },
  'utcOffset':                        { 'default': 0 },
  'utcTimeSynchronizationRecipients': { 'default': [] },
  'validSamples':                     { 'default': 0 },
  'valueBeforeChange':                { 'default': 0 },
  'valueSet':                         { 'default': 0 },
  'valueSource':                      { 'default': ValueSource(none=Null()) },
  'valueSourceArray':                 { 'default': ArrayOf(ValueSource)([ValueSource(none=Null()) for i in range(16)]) },
  'valueChangeTime':                  { 'default': defaultDateTime },
  'varianceValue':                    { 'default': -float('nan') },
  'weeklySchedule':                   { 'default': [DailySchedule(daySchedule=[]) for i in range(7)] },
  'windowInterval':                   { 'default': 0 },
  'windowSamples':                    { 'default': 0 },
}
